language: c
services:
  -docker

before-script:
  - pip install docker-compose
  - sudo apt-get install ruby ruby-bundler ruby-dev build-essential
  - git clone https://github.com/hivehelsinki/norminette-client.git ~/.norminette/
  - cd ~/.norminette/
  - bundle
  - echo 'alias norminette="~/.norminette/norminette.rb"' >> ~/.zshrc source ~/.zshrc
  - norminette .
