language: c

install:
  - sudo apt-get install ruby ruby-bundler ruby-dev build-essential
  - git clone https://github.com/hivehelsinki/norminette-client.git norminette
  - cd norminette
  - bundle
  - cd ..

  # - norminette/norminette.rb . > norm.txt
  # - grep "Error" norm.txt | wc -l > norm.txt
  # - test norminette/norminette.rb . | grep "Error" | wc -l

script:
  - if [[ $(norminette/norminette.rb . | grep 'Error') ]]; then false; else true; fi
